window.R = {
    audio: {
        game: {
        //    
        }
    },
    image: {
        
        },
    string: {
        app_name: "嗒嗒编程",
        // language_en: "English",
        language_zh_cn: "简体中文",
        // language_zh_tw: "繁體中文",
        access_denied: "访问被拒绝!!!",
        ace_completer_keywords: "关键字",
        ace_completer_method: "方法",
        ace_completer_obj: "对象",
        ace_completer_attr: "属性",
        ace_Tip_player: "dada:\n 小飞侠嗒嗒，游戏第一主角",
        ace_Tip_moveLeft: "moveLeft([step])->None:\n 向左移动step(默认为1)格子数，无返回值\n step:int 可选，数字，默认为1",
        ace_Tip_moveUp: "moveUp([step])->None:\n 向上移动step(默认为1)格子数，无返回值\n step:int 可选，数字，默认为1",
        ace_Tip_moveRight: "moveRight([step])->None:\n 向右移动step(默认为1)格子数，无返回值\n step:int 可选，数字，默认为1",
        ace_Tip_moveDown: "moveDown([step])->None:\n 向下移动step(默认为1)格子数，无返回值\n step:int 可选，数字，默认为1",
        ace_Tip_pickUp: "pickUp()->None:\n 捡起地上的东西，无返回值",
        ace_Tip_putDown: "put down:\n  use...for...",
        ace_Tip_true: "True:\n 布尔值，True 代表真",
        ace_Tip_false: "False:\n  布尔值，False 代表假",
        ace_Tip_while: "while:\n 如果...就一直.....",
        ace_Tip_for: "for:\n for循环是一个次数固定的循环",
        ace_Tip_if: "if:\n 分支判断句式关键字：表示如果",
        ace_Tip_else: "else:\n 分支判断句式关键字：表示否则",
        ace_Tip_def: "def:\n 用于封装函数的关键字",
        ace_Tip_return: "return:\n return用于定义函数的返回值",
        ace_Tip_break: "break:\n break语句用在while和for循环中，终止当前循环的语句",
        ace_Tip_continue: "continue:\n continue用于跳过当前循环的剩余语句",
        header_menu_sign_up: "注册",
        header_menu_sign_in: "登录",
        header_menu_sign_out: "退出",
        header_menu_student: "学生主页",
        header_menu_teacher: "教师看板",
        header_menu_school: "管理面板",
        header_menu_agent: "代理商主页",
        header_menu_admin: "管理员主页",
        header_menu_explain: "指令说明",
        header_menu_support: "技术支持",
        verify_slider_refuse: "滑动验证",
        verify_slider_passed: "验证通过",
        message_hint_default: "请在这写下你的提示信息",
        message_hint_chapter01: "认真想一想！",
        message_win_default: "请在这写下你的胜利信息",
        message_win_chapter01: "恭喜你成功了！",
        message_lose_default: "请在这写下你的失败信息",
        message_lose_chapter01: "Sorry You're dead！",
        message_welcome_default: "请在这写下你的欢迎语",
        message_welcome_chapter01: "Let's get started！",
        parser_unexpected_character: "无效字符'%0p'",
        parser_incomplete_segment: "丢失了'%0p'",
        parser_stray_character: "游离字符'%0p'",
        parser_unexpected_indent: "不合法的缩进",
        parser_unexpected_token: "在'%1p'前面丢失'%0p'",
        parser_invalid_syntax: "无效的语法'%0p'",
        parser_empty_block: "空的代码块",
        parser_unexpected_end_of_input: "结束缺少'%0p'",
        parser_stray_token: "游离的词'%0p'",
        parser_undefined_variable: "变量'%0p'未定义",
        parser_variable_override: "'%0p' 覆盖了内建变量",
        parser_invalid_left_value: "向非左值赋值",
        vm_unsupported_node: "不支持的语法'%0p'",
        vm_not_function: "'%0p'不是一个函数",
        vm_not_iterable: "'%0p'不可迭代",
        vm_read_property: "不能读取'%1p'的属性'%0p'",
        vm_not_subscriptable: "'%0p'不是数组",
        vm_integer_indices: "数组索引必须是整数值",
        vm_string_indices: "字典索引必须是字符串值",
        vm_in_not_iterable: "'in'需要可迭代对象作为右操作数",
        vm_in_string: "'in [string]'需要字符串作为左操作数",
        vm_miss_parameters: "%0p()丢失了%1p个参数: %2p",
        vm_over_parameters: "%0p()仅需要%1p个参数 但是提供了%2p个",
        vm_unknown: "未知的解释器错误",
        vmrt_location: "第%0p行",
        vmrt_undeclared: "'%0p'没有声明",
        vmrt_move_to: "moveTo()需要一个游戏对象或两个数字",
        vmrt_move: "%0p()需要一个数字",
        vmrt_say: "say()需要一个字符串、数字或布尔值",
        vmrt_onkey: "onKey()需要一个函数",
        vmrt_onclick: "onKey()需要一个函数",
        vmrt_pick_up: "pickUp()需要一个[thing]对象或自动搜索",
        vmrt_give_to: "give()需要一个[trader]对象与一个[thing]对象或自动搜索",
        vmrt_put_down: "putDown()需要一个[thing]对象或自动搜索",
        vmrt_backpack_select: "backpack.select()需要一个整数",
        vmrt_backpack_find: "backpack.find()需要一个字符串",
        vmrt_out_of_range: "数组索引超出范围",
        vmrt_range: "range()需要一至三个整数",
        vmrt_readonly: "'%0p' 是只读属性",
        challenge_number: "第%0p关",
        challenge_main_menu_reset: "重置",
        challenge_main_menu_run: "运行",
        challenge_main_menu_stop: "终止",
        challenge_settlement_restart: "重新开始",
        challenge_settlement_next: "下一关卡",
        challenge_settlement_knowledge: "知识点",
        challenge_settlement_known: "我知道了",
        challenge_settlement_learning_target: "学习目标",
        challenge_settlement_copy_to_editor: "复制到游戏中",
        challenge_dialog_skip: "跳过",
        challenge_control_panel_normal: "正常速度",
        challenge_control_panel_double: "2倍提速",
        challenge_control_panel_play: "音乐",
        challenge_control_panel_mute: "静音",
        challenge_control_panel_record: "我的答案",
        challenge_control_panel_answer: "参考答案",
        challenge_control_panel_map: "地图",
        challenge_control_panel_prompt: "提示",
        challenge_control_panel_target: "知识点",
        challenge_control_panel_popup: "菜单",
        challenge_tutorial_0: "嗖！要到达这里进入传送阵哦！",
        complete_message_1: "Well Done !!!",
        failure_message_1: "Sorry...",
        challenge_target_1: "让嗒嗒向下移动1个格子的距离<br>dada.moveDown()",
        challenge_prompt_1: "我们一定要帮嗒嗒到达传送阵寻找水晶碎片！",
        ace_Tip_pili: "Pili :\n 游戏最后登场的第三主角，本体是一朵云",
        ace_Tip_pala: "Pala :\n 游戏第二登场主角，精灵族",
        ace_Tip_leafy: "Leafy :\n 叶子怪丽菲，小精灵很怕她",
        ace_Tip_woody: "Woody :\n 树怪伍迪特别喜欢收集一些东西",
        ace_Tip_masker: "Masker :\n 遇着马克要躲远点",
        ace_Tip_winter: "Winter :\n 你永远猜不到温特里面会不会有个马克",
        ace_Tip_rolling: "Rolling :\n 罗琳是长得跟风扇一样的神奇生物",
        ace_Tip_crystal: "crystal :\n 必须收集完所有的水晶碎片",
        ace_Tip_portal: "portal:\n portal是目的地",
        ace_Tip_bud: "Bud:\n 巴德是还在冬眠状态的的种子.",
        ace_Tip_item: "item:\n 收集物有两种：书（book）和肉（meat）",
        ace_Tip_moveTo: "moveTo(obj)->None:\n 向目的地移动，无返回值\n obj:必填，游戏对象或者{x,y}:x是目的地X坐标，y是目的地y坐标",
        ace_Tip_say: "say(obj)->None:\n 向目的地移动，无返回值\n obj:必填，字符串、数字、布尔值 ",
        ace_Tip_give: "give()->None:\n 把手里的物品给面前的树怪伍迪，无返回值",
        ace_Tip_blow: "blow()->None:\n 让小云仙噼里吹风，无返回值",
        ace_Tip_rain: "rain()->None:\n 让小云仙噼里下雨，无返回值",
        ace_Tip_shine: "shine()->None:\n 让小云仙噼里出太阳，无返回值",
        ace_Tip_thunder: "thunder()->None:\n 让小云仙噼里打雷，无返回值",
        ace_Tip_ice: "ice()->None:\n 让小精灵啪啦在当前格放一个冰块，无返回值",
        ace_Tip_recover: "recover()->None:\n 让小精灵啪啦恢复魔法值，无返回值",
        ace_Tip_ratedSpeed: "ratedSpeed->数字:\n 能够让转转罗琳转起来的速度 ",
        ace_Tip_mana: "mana->数字:\n 表示小精灵当前的魔法值 ",
        ace_Tip_inCrack: "inCrack->布尔值:\n 表示小精灵当前的是否悬空 ",
        ace_Tip_plant: "plant->字符串:\n 小种子巴德的种类\n 可能值为 ‘Dull’或‘Lively’ ",
        ace_Tip_isMature: "isMature->布尔值:\n 表示小种子巴德当前的是否成熟 ",
        ace_Tip_had: "had->字符串:\n 树怪伍迪现在手中有的东西\n 可能值为 ‘crystal’、‘meat’或‘book’ ",
        ace_Tip_wish: "wish->字符串:\n 树怪伍迪想要的东西\n 可能值为 ‘crystal’、‘meat’或‘book’ ",
        ace_Tip_temperature: "temperature->数字:\n  雪人当前的温度",
        ace_Tip_core: "core->布尔值:\n 雪人融化后是否有土著在里面",
        ace_Tip_isSleeping: "isSleeping->布尔值:\n 土著是否睡着了",
        ace_Tip_isPlaying: "isPlaying->布尔值:\n 土著是否在玩耍",
        ace_Tip_speed: "speed->数字:\n 转转罗琳当前的速度 ",
        ace_Tip_type: "type->字符串:\n 收集物的类型 ",
        ace_Tip_elif: "elif:\n 分支判断句式关键字：表示否则若",
        challenge_settlement_jump: "尝试这一关",
        challenge_answer_copy: "复制代码到游戏中",
        challenge_tutorial_1: "点点我吧。",
        challenge_tutorial_2: "点击鼠标左键看看。",
        challenge_tutorial_3: "点击“moveRight”试试。",
        challenge_tutorial_4: "这里有通关的技巧哦！",
        challenge_tutorial_5: "看看这一关卡的知识点是什么？能帮助你通关哦！",
        challenge_tutorial_6: "小喇叭可以关掉声音哦。",
        challenge_tutorial_7: "点亮“速度”，可以加速哦！",
        challenge_tutorial_8: "可以在指令栏里面调用需要使用的指令哦！",
        challenge_tutorial_9: "滑动滚轮可以使地图放大缩小哦，你试试吧！",
        challenge_tutorial_10: "想要打开传送阵,需要先获得水晶碎片哦。",
        challenge_tutorial_11: "嗒嗒需要使用“捡起pickUp()”指令，将书或者肉捡起来，再使用“给give()”指令，与树怪Woody交换。否则，传送阵将不会打开。",
        challenge_tutorial_12: "小心哦，叶子怪最喜欢吓唬小精灵，所以不要让小精灵啪啦靠近它周围一圈的距离。",
        challenge_tutorial_13: "注意哦，土著小人Masker醒着的时候进入他的领地会被揍的，要等他睡着了再通过啊。",
        challenge_tutorial_1000: "用键盘输入： dada.moveDown()",
        challenge_victory_1: "真棒！一下就做到了！",
        challenge_victory_2: "你成功的破解了这一关！",
        challenge_victory_3: "厉害了，空间感很强嘛！",
        challenge_victory_4: "过关了，你还挺厉害的嘛",
        challenge_victory_5: "是不是比想象中要简单呢！",
        challenge_victory_6: "干得漂亮！",
        challenge_victory_7: "学的很快哦！",
        challenge_victory_8: "看来你的功力还真是超出我的预料！哈哈，我猜错了。",
        challenge_victory_9: "你现在用的是循环的概念哦！",
        challenge_victory_10: "这个方法是不是很棒！",
        challenge_victory_11: "干得漂亮，没想到你进步的这么快！",
        challenge_victory_12: "你发现其中的规律了，棒极了！",
        challenge_victory_13: "不错哦，你已经有一些基本的编码技巧了。",
        challenge_victory_14: "确认过眼神，你已经练就了火眼金睛。",
        challenge_victory_15: "你太棒了，这样都可以，超级组合诞生！",
        challenge_victory_16: "越来越进步了！",
        challenge_victory_17: "写出简洁代码的前提是你有清晰的逻辑思维",
        challenge_victory_18: "干得漂亮，没想到你进步的这么快！",
        challenge_victory_19: "这，太神奇了！",
        challenge_victory_20: "你们真是合作无间的好伙伴！",
        challenge_victory_21: "为自己的努力加油鼓鼓掌吧！",
        challenge_victory_22: "只有收集所有的水晶碎片，才能封印住怪物的洞口，战斗吧，嗒嗒！",
        challenge_victory_23: "成功的感觉真好！",
        challenge_victory_24: "没有什么是能比一个编写完整的循环指令更让我快乐的了！",
        challenge_victory_25: "这么难的关卡你都能挑战成功，真的是很厉害！",
        challenge_victory_26: "你让嗒嗒充满了知识的力量！",
        challenge_victory_27: "你真是个小天才.",
        challenge_victory_28: "这就对了！",
        challenge_victory_29: "我们来看看这关你能不能够挑战成功？",
        challenge_victory_30: "是不是很有成就感，这一关是考验你是否真的掌握了前面学习的知识。",
        challenge_victory_31: "再接再厉",
        challenge_victory_32: "你明白重点了吗？",
        challenge_victory_33: "跟着我啪啦走，没问题的啦。",
        challenge_victory_34: "为自己的努力加油鼓鼓掌吧！",
        challenge_victory_35: "有了啪啦这个小帮手，你是不是更容易通关了呢？",
        challenge_victory_36: "真是等待已久的胜利啊！",
        challenge_victory_37: "不错，你已经学会了越来越多的编码技巧。",
        challenge_victory_38: "叶子怪们或许很厉害，但是我们比它们更有智慧！",
        challenge_victory_39: "希望你已经知道了什么叫通力合作，所向无敌",
        challenge_victory_40: "不得不夸夸你了，给你封一个小神童的称号",
        challenge_victory_41: "你明白重点了吗？",
        challenge_victory_42: "这就对了！",
        challenge_victory_43: "大胆假设，小心求证，你懂了吗？",
        challenge_victory_44: "跟着我啪啦走，没问题的啦。",
        challenge_victory_45: "啪啦啪啦小魔仙变变变！",
        challenge_victory_46: "收集了这么多的水晶碎片，很快就能凑成完整水晶了",
        challenge_victory_47: "学的很快哦！",
        challenge_victory_48: "简洁的代码，看起来是不是很赏心悦目",
        challenge_victory_49: "循环是一个让你的代码重复执行的好方法。",
        challenge_victory_50: "很开心吧？",
        challenge_victory_51: "我真的以你为荣！",
        challenge_victory_52: "哈哈，成功了！",
        challenge_victory_53: "这么难的关卡你能挑战成功真是很厉害哦！",
        challenge_victory_54: "你的嗒嗒真的是好厉害呀！",
        challenge_victory_55: "你真棒，没有和马克大打一架",
        challenge_victory_56: "太棒了，我确定接下来我们要多多利用这个指令。",
        challenge_victory_57: "哈哈，你有看到它睡觉流的口水吗？",
        challenge_victory_58: "没有什么是比编写完整的循环指令更让我快乐的了。",
        challenge_victory_59: "现在没有那么恐怖了对吗？",
        challenge_victory_60: "啦啦啦啦，知道它的弱点，就再不怕土著Masker了！",
        challenge_victory_61: "睡吧睡吧，你睡着了我就能过去了。",
        challenge_victory_62: "了不起，我想我终于安全了。",
        challenge_victory_63: "哟，很不错！",
        challenge_victory_64: "你进步的很快，这个知识点掌握的很好！",
        challenge_victory_65: "土著们分别在不同的时间里才睡着，这样的逻辑你都能掌握，厉害了！",
        challenge_victory_66: "土著小人可是唱高音的，好听吗？",
        challenge_victory_67: "这真的是一个得来不易的胜利",
        challenge_victory_68: "每次遇到困难，啪啦都会给我帮助，我们要珍惜这样的朋友！",
        challenge_victory_69: "我们绝不停止，直到我们拿到所有的水晶碎片通关。",
        challenge_victory_70: "赞美的语言都不能形容你的聪明才智！",
        challenge_victory_71: "这个画面太美了，棒棒哒！",
        challenge_victory_72: "酷！新本领掌握的很好嘛！",
        challenge_victory_73: "不得不说你简直优秀！",
        challenge_victory_74: "后面的会更难，准备好了吗？",
        challenge_victory_75: "这么难的知识点都能理解，你很有编程的天分！",
        challenge_victory_76: "萝卜青菜各有所爱，Woody是都喜欢呢！",
        challenge_victory_77: "这么难你都能通关，厉害！",
        challenge_victory_78: "愉快的开始从一个地方走到另一个地方了。",
        challenge_victory_79: "几个主角身上都能用moveTo()，棒不棒。",
        challenge_victory_80: "",
        challenge_victory_81: "",
        challenge_victory_82: "",
        challenge_victory_83: "",
        challenge_victory_84: "",
        challenge_victory_85: "",
        challenge_victory_86: "",
        challenge_victory_87: "",
        challenge_victory_88: "",
        challenge_victory_89: "",
        challenge_victory_90: "",
        challenge_victory_91: "",
        challenge_victory_92: "",
        challenge_victory_93: "",
        challenge_victory_94: "",
        challenge_victory_95: "",
        challenge_victory_96: "",
        challenge_victory_97: "",
        challenge_victory_98: "",
        challenge_victory_99: "",
        challenge_victory_100: "",
        challenge_victory_101: "",
        challenge_victory_102: "",
        challenge_victory_103: "",
        challenge_victory_104: "",
        challenge_victory_105: "",
        challenge_victory_106: "",
        challenge_victory_107: "",
        challenge_victory_108: "",
        challenge_victory_109: "",
        challenge_victory_110: "",
        challenge_victory_111: "",
        challenge_victory_112: "",
        challenge_victory_113: "",
        challenge_victory_114: "",
        challenge_victory_115: "",
        challenge_victory_116: "",
        challenge_victory_117: "",
        challenge_victory_118: "",
        challenge_victory_119: "",
        challenge_victory_120: "",
        challenge_victory_121: "",
        challenge_victory_122: "",
        challenge_victory_123: "",
        challenge_victory_124: "",
        challenge_victory_125: "",
        challenge_victory_126: "",
        challenge_victory_127: "",
        challenge_victory_128: "",
        challenge_victory_129: "",
        challenge_victory_130: "",
        challenge_victory_131: "",
        challenge_victory_132: "",
        challenge_victory_133: "",
        challenge_victory_134: "",
        challenge_victory_135: "",
        challenge_victory_136: "",
        challenge_victory_137: "",
        challenge_victory_138: "",
        challenge_victory_139: "",
        challenge_victory_140: "",
        challenge_victory_141: "",
        challenge_victory_142: "",
        challenge_victory_143: "",
        challenge_victory_144: "",
        challenge_victory_145: "",
        challenge_victory_146: "",
        challenge_victory_147: "",
        challenge_victory_148: "",
        challenge_victory_149: "",
        challenge_victory_150: "",
        challenge_victory_151: "",
        challenge_victory_152: "",
        challenge_victory_153: "",
        challenge_victory_154: "",
        challenge_victory_155: "",
        challenge_victory_156: "",
        challenge_victory_157: "",
        challenge_victory_158: "",
        challenge_victory_159: "",
        challenge_victory_160: "",
        challenge_victory_161: "",
        challenge_victory_162: "",
        challenge_victory_163: "你用智慧打败了叶子怪，棒极了！",
        challenge_victory_164: "嗒嗒成功的通关了，开心吗？",
        challenge_victory_165: "恭喜你，你选择了正确的路线",
        challenge_victory_166: "没有什么能够阻挡你前进的道路！",
        challenge_victory_167: "说真的，我都有点佩服你了O(∩_∩)O",
        challenge_victory_168: "",
        challenge_victory_169: "",
        challenge_victory_170: "",
        challenge_victory_171: "",
        challenge_victory_172: "",
        challenge_victory_173: "",
        challenge_victory_174: "土著马克说他很喜欢这个新名字！",
        challenge_victory_175: "啊哈哈～还真是什么都难不住你呢！",
        challenge_victory_176: "",
        challenge_victory_177: "",
        challenge_victory_178: "",
        challenge_victory_179: "",
        challenge_victory_180: "",
        challenge_victory_181: "",
        challenge_failure_1: "我们再试试！",
        challenge_failure_2: "哎呀，出错了，别着急，好好数数看。",
        challenge_failure_3: "头晕了吧？加油！",
        challenge_failure_4: "别怕，你肯定能行！",
        challenge_failure_5: "有点不太对，你再想想。",
        challenge_failure_6: "不要放弃，再试试。",
        challenge_failure_7: "你一定可以做得到",
        challenge_failure_8: "注意细节哦。",
        challenge_failure_9: "你大胆去尝试一下不是很好吗？",
        challenge_failure_10: "我们再想一想！",
        challenge_failure_11: "呃，看来这一关你需要再思考一下。",
        challenge_failure_12: "这一关确实很难，加油。",
        challenge_failure_13: "看看提示内容，注意一下步数和方向。",
        challenge_failure_14: "不是你的错，是编关老师故意的。",
        challenge_failure_15: "再试试！",
        challenge_failure_16: "别怕，你肯定能行！",
        challenge_failure_17: "小脑袋转起来。",
        challenge_failure_18: "你一定可以做得到！",
        challenge_failure_19: "没什么大不了！",
        challenge_failure_20: "波若波若蜜，让我通关穿越吧。",
        challenge_failure_21: "冷静分析一下没通关的原因，顺序是否正确。",
        challenge_failure_22: "再试试吧！",
        challenge_failure_23: "水晶碎片在等你，加油通关吧。",
        challenge_failure_24: "别怕，你肯定能行",
        challenge_failure_25: "要看清楚后再施法哦！",
        challenge_failure_26: "新指令需要多试几次。",
        challenge_failure_27: "没什么大不了。",
        challenge_failure_28: "不要放弃，再努力试一下。",
        challenge_failure_29: "你一定可以做得到",
        challenge_failure_30: "不是你的错，是编关老师太严格了。",
        challenge_failure_31: "不要忘记了啪啦会飞。",
        challenge_failure_32: "有点不太对，你再想一想...",
        challenge_failure_33: "我就不信我把我所有所学用上，不能赢了你们这些小怪物！",
        challenge_failure_34: "我们再试试",
        challenge_failure_35: "头晕了吧？加油！",
        challenge_failure_36: "别怕，你肯定能行！",
        challenge_failure_37: "有点不太对，你再想想。",
        challenge_failure_38: "不要放弃，再试试。",
        challenge_failure_39: "你一定可以做得到",
        challenge_failure_40: "注意细节哦",
        challenge_failure_41: "你大胆去尝试一下不是很好吗？",
        challenge_failure_42: "我们再想一想！",
        challenge_failure_43: "呃，看来这一关你需要再思考一下。",
        challenge_failure_44: "这一关确实很难，加油。",
        challenge_failure_45: "不是你的错，是编关老师故意的。",
        challenge_failure_46: "再试试！",
        challenge_failure_47: "别怕，你肯定能行！",
        challenge_failure_48: "小脑袋转起来。",
        challenge_failure_49: "没什么大不了！",
        challenge_failure_50: "波若波若蜜，让我通关穿越吧。",
        challenge_failure_51: "可能……啪啦还差点魔法值？",
        challenge_failure_52: "再试试吧！",
        challenge_failure_53: "再试试吧！",
        challenge_failure_54: "别怕，你肯定能行",
        challenge_failure_55: "程序员名言：没有什么做不到的，只是需要时间",
        challenge_failure_56: "键盘在手，水晶我有，加油。",
        challenge_failure_57: "地球是圆的，代码无所不能，总会成功的",
        challenge_failure_58: "来来来，再来！",
        challenge_failure_59: "新指令需要多试几次。",
        challenge_failure_60: "没什么大不了。",
        challenge_failure_61: "不要放弃，再努力试一下。",
        challenge_failure_62: "你一定可以做得到",
        challenge_failure_63: "不是你的错，是编关老师太严格了。",
        challenge_failure_64: "很接近了，继续努力吧。",
        challenge_failure_65: "有点不太对，你再想一想...",
        challenge_failure_66: "我就不信，把我所有所学用上，赢不了你们这些小怪物！",
        challenge_failure_67: "我承认这一关很难，你要加油。",
        challenge_failure_68: "我们再试试",
        challenge_failure_69: "头晕了吧？加油！",
        challenge_failure_70: "别怕，你肯定能行！",
        challenge_failure_71: "有点不太对，你再想想。",
        challenge_failure_72: "不要放弃，再试试。",
        challenge_failure_73: "你一定可以做得到",
        challenge_failure_74: "注意细节哦。",
        challenge_failure_75: "你大胆去尝试一下不是很好吗？",
        challenge_failure_76: "我们再想一想！",
        challenge_failure_77: "这一关确实很难，加油。",
        challenge_failure_78: "呃，看来这一关你需要再思考一下。",
        challenge_failure_79: "不是你的错，是编关老师故意的。",
        challenge_failure_80: "再试试！",
        challenge_failure_81: "别怕，你肯定能行！",
        challenge_failure_82: "小脑袋转起来。",
        challenge_failure_83: "没什么大不了！",
        challenge_failure_84: "波若波若蜜，让我通关穿越吧。",
        challenge_failure_85: "冷静分析一下没通关的原因，顺序是否正确。",
        challenge_failure_86: "再试试吧！",
        challenge_failure_87: "水晶碎片在等你，加油通关吧。",
        challenge_failure_88: "别怕，你肯定能行",
        challenge_failure_89: "键盘在手，水晶我有，加油。",
        challenge_failure_90: "程序员名言：没有什么做不到的，只是需要时间",
        challenge_failure_91: "地球是圆的，代码无所不能，总会成功的",
        challenge_failure_92: "来来来，再来！",
        challenge_failure_93: "新指令需要多试几次。",
        challenge_failure_94: "没什么大不了。",
        challenge_failure_95: "不要放弃，再努力试一下。",
        challenge_failure_96: "你一定可以做得到",
        challenge_failure_97: "不是你的错，是编关老师太严格了。",
        challenge_failure_98: "很接近了，继续努力吧。",
        challenge_failure_99: "有点不太对，你再想一想...",
        challenge_failure_100: "我就不信我把我所有所学用上，不能赢了你们这些小怪物！",
        challenge_failure_101: "我承认这一关很难，你要加油。",
        challenge_failure_102: "我们再试试",
        challenge_failure_103: "头晕了吧？加油！",
        challenge_failure_104: "别怕，你肯定能行！",
        challenge_failure_105: "有点不太对，你再想想。",
        challenge_failure_106: "不要放弃，再试试。",
        challenge_failure_107: "你一定可以做得到",
        challenge_failure_108: "注意细节哦。",
        challenge_failure_109: "你大胆去尝试一下不是很好吗？",
        challenge_failure_110: "我们再想一想！",
        challenge_failure_111: "呃，看来这一关你需要再思考一下。",
        challenge_failure_112: "这一关确实很难，加油。",
        challenge_failure_113: "不是你的错，是编关老师故意的。",
        challenge_failure_114: "再试试！",
        challenge_failure_115: "别怕，你肯定能行！",
        challenge_failure_116: "小脑袋转起来。",
        challenge_failure_117: "没什么大不了！",
        challenge_failure_118: "波若波若蜜，让我通关穿越吧。",
        challenge_failure_119: "冷静分析一下没通关的原因，顺序是否正确。",
        challenge_failure_120: "再试试吧！",
        challenge_failure_121: "水晶碎片在等你，加油通关吧。",
        challenge_failure_122: "别怕，你肯定能行",
        challenge_failure_123: "键盘在手，水晶我有，加油。",
        challenge_failure_124: "程序员名言：没有什么做不到的，只是需要时间",
        challenge_failure_125: "地球是圆的，代码无所不能，总会成功的",
        challenge_failure_126: "来来来，再来！",
        challenge_failure_127: "新指令需要多试几次。",
        challenge_failure_128: "没什么大不了。",
        challenge_failure_129: "不要放弃，再努力试一下。",
        challenge_failure_130: "你一定可以做得到",
        challenge_failure_131: "不是你的错，是编关老师太严格了。",
        challenge_failure_132: "很接近了，继续努力吧。",
        challenge_failure_133: "有点不太对，你再想一想...，",
        challenge_failure_134: "我就不信我把我所有所学用上，不能赢了你们这些小怪物！",
        challenge_failure_135: "我承认这一关很难，你要加油。",
        challenge_failure_136: "",
        challenge_failure_137: "",
        challenge_failure_138: "",
        challenge_failure_139: "",
        challenge_failure_140: "",
        challenge_failure_141: "",
        challenge_failure_142: "",
        challenge_failure_143: "",
        challenge_failure_144: "",
        challenge_failure_145: "",
        challenge_failure_146: "",
        challenge_failure_147: "",
        challenge_failure_148: "",
        challenge_failure_149: "",
        challenge_failure_150: "",
        challenge_failure_151: "",
        challenge_failure_152: "",
        challenge_failure_153: "",
        challenge_failure_154: "",
        challenge_failure_155: "",
        challenge_failure_156: "",
        challenge_failure_157: "",
        challenge_failure_158: "",
        challenge_failure_159: "",
        challenge_failure_160: "",
        challenge_failure_161: "",
        challenge_failure_162: "",
        challenge_failure_163: "不要放弃，再努力试一下。",
        challenge_failure_164: "波若波若蜜，让我通关穿越吧。",
        challenge_failure_165: "小脑袋转起来。",
        challenge_failure_166: "指挥好小精灵啪啦是很重要的",
        challenge_failure_167: "差一点点就能到终点了。",
        challenge_failure_168: "",
        challenge_failure_169: "",
        challenge_failure_170: "",
        challenge_failure_171: "",
        challenge_failure_172: "",
        challenge_failure_173: "",
        challenge_failure_174: "有点不太对，你再想想。",
        challenge_failure_175: "别怕，你肯定能行！",
        challenge_failure_176: "",
        challenge_failure_177: "",
        challenge_failure_178: "",
        challenge_failure_179: "",
        challenge_failure_180: "",
        challenge_failure_181: "",
        challenge_target_2: "让嗒嗒向下移动1个格子的距离<br>dada.moveDown()",
        challenge_target_3: "让嗒嗒向下移动1个格子的距离<br>dada.moveDown()<br>让嗒嗒向上移动1个格子的距离<br>dada.moveUp()<br>让嗒嗒向左移动1个格子的距离<br>dada.moveLeft() <br>让嗒嗒向右移动1个格子的距离<br>dada.moveRight()",
        challenge_target_4: "让嗒嗒向下移动1个格子的距离<br>dada.moveDown()<br>让嗒嗒向上移动1个格子的距离<br>dada.moveUp()<br>让嗒嗒向左移动1个格子的距离<br>dada.moveLeft() <br>让嗒嗒向右移动1个格子的距离<br>dada.moveRight()",
        challenge_target_5: "给移动函数传入一个整数参数可以移动对应的格子数，例如：<br>让嗒嗒向右移动5个格子的距离<br>dada.moveRight(5)",
        challenge_target_6: "给移动函数传入一个整数参数可以移动对应的格子数，例如：<br>让嗒嗒向下移动3个格子的距离<br>dada.moveDown(3)<br>让嗒嗒向上移动5个格子的距离<br>dada.moveUp(5)<br>让嗒嗒向左移动6个格子的距离<br>dada.moveLeft(6) <br>让嗒嗒向右移动2个格子的距离<br>dada.moveRight(2)",
        challenge_target_7: "给移动函数传入一个整数参数可以移动对应的格子数，例如：<br>让嗒嗒向下移动3个格子的距离<br>dada.moveDown(3)<br>让嗒嗒向上移动5个格子的距离<br>dada.moveUp(5)<br>让嗒嗒向左移动6个格子的距离<br>dada.moveLeft(6) <br>让嗒嗒向右移动2个格子的距离<br>dada.moveRight(2)",
        challenge_target_8: "给移动函数传入一个整数参数可以移动对应的格子数，例如：<br>让嗒嗒向下移动3个格子的距离<br>dada.moveDown(3)<br>让嗒嗒向上移动5个格子的距离<br>dada.moveUp(5)<br>让嗒嗒向左移动6个格子的距离<br>dada.moveLeft(6) <br>让嗒嗒向右移动2个格子的距离<br>dada.moveRight(2)",
        challenge_target_9: "while True是循环语句的一种，用来处理在某个条件成立时要做的重复的事情，例如：<br>while True:<br>    dada.moveUp()<br>这样会让嗒嗒一直往上走，除非嗒嗒掉入裂隙或到达终点。",
        challenge_target_10: "while True是循环语句的一种，用来处理在某个条件成立时要做的重复的事情，例如：<br>while True:<br>    dada.moveUp()<br>这样会让嗒嗒一直往上走，除非嗒嗒掉入裂隙或到达终点。",
        challenge_target_11: "空白在Python中是重要的。事实上行首的空白是重要的。它称为缩进。在逻辑行首的空白（空格和制表符）用来决定逻辑行的缩进层次，从而用来决定语句的分组。这意味着同一层次的语句必须有相同的缩进。每一组这样的语句称为一个块。",
        challenge_target_12: "如果要用while True来让嗒嗒走重复的路径，一定要确保已经激活的传送阵在重复的路径上，要不然嗒嗒会一直走下去。",
        challenge_target_13: "while True循环里面可以写各种需要重复做的事情，例如：<br>while True:<br>    dada.moveUp(2)<br>    dada.moveDown(2)<br>这样的代码运行后嗒嗒会一直向上移动两个格子的距离，然后再向下移动两个格子的距离，直到你停止程序运行。",
        challenge_target_14: "如果要用while True来让嗒嗒走重复的路径，一定要确保已经激活的传送阵在重复的路径上，要不然嗒嗒会一直走下去。",
        challenge_target_15: "在地图上经常能够见到大大小小的裂隙，嗒嗒碰到裂隙的时候会掉下去。小精灵啪啦的ice()方法可以释放冰魔法填补裂隙，这样嗒嗒就可以通过有裂隙的地块。但是需要注意，啪啦释放在没有裂隙的地块上的冰魔法会成为障碍物。",
        challenge_target_16: "在地图上经常能够见到大大小小的裂隙，嗒嗒碰到裂隙的时候会掉下去。小精灵啪啦的ice()方法可以释放冰魔法填补裂隙，这样嗒嗒就可以通过有裂隙的地块。但是需要注意，啪啦释放在没有裂隙的地块上的冰魔法会成为障碍物。",
        challenge_target_17: "啪啦的移动方式和嗒嗒一样，像这样：<br>让啪啦向下移动3个格子的距离<br>pala.moveDown(3)<br>让啪啦向上移动5个格子的距离<br>pala.moveUp(5)<br>让啪啦向左移动6个格子的距离<br>pala.moveLeft(6) <br>让啪啦向右移动2个格子的距离<br>pala.moveRight(2)",
        challenge_target_18: "啪啦可以通过低矮的障碍物（草垛，小石墩），但是太高（图腾，大石碑）的就过不去了。",
        challenge_target_19: "写在while True里面的pala.ice()可以让啪啦循环的释放冰魔法，但是要注意啪啦释放魔法的位置。",
        challenge_target_20: "找好路径，啪啦先去前面填补裂隙，让嗒嗒在后面跟着。",
        challenge_target_21: "水晶碎片是通过的必要条件之一，只有收集完地图上所有的水晶碎片的时候，传送门才会激活。",
        challenge_target_22: "水晶碎片是通过的必要条件之一，只有收集完地图上所有的水晶碎片的时候，传送门才会激活。",
        challenge_target_23: "水晶碎片是通过的必要条件之一，只有收集完地图上所有的水晶碎片的时候，传送门才会激活。没有激活的传送门即使路过也不会被传送到下一关",
        challenge_target_24: "while True循环里面可以写各种需要重复做的事情，例如：<br>while True:<br>    dada.moveUp(2)<br>    dada.moveDown(2)<br>这样的代码运行后嗒嗒会一直重复向上移动两个格子的距离，然后再向下移动两个格子的距离，直到程序停止运行。",
        challenge_target_25: "while True循环里面可以写各种需要重复做的事情，例如：<br>while True:<br>    dada.moveUp(2)<br>    dada.moveDown(2)<br>这样的代码运行后嗒嗒会一直重复向上移动两个格子的距离，然后再向下移动两个格子的距离，直到程序停止运行。",
        challenge_target_26: "dada.pick()方法可以让嗒嗒捡起地面上的收集物（书或者肉）<br>当嗒嗒靠近树怪伍迪身边时dada.give()方法可以用嗒嗒手里的东西交换树怪伍迪拥有的东西。<br>树怪伍迪在交换到自己喜欢的东西时会走开。",
        challenge_target_27: "树怪伍迪身上有时会藏着水晶碎片。树怪伍迪身上的水晶碎片也是必须要收集。",
        challenge_target_28: "dada.pick()方法可以让嗒嗒捡起地面上的收集物（书或者肉）<br>当嗒嗒手里有东西还要去捡别的东西的时候，手里的东西会掉落。",
        challenge_target_29: "dada.pick()方法可以让嗒嗒捡起地面上的收集物（书或者肉）<br>当嗒嗒靠近树怪伍迪身边时dada.give()方法可以用嗒嗒手里的东西交换树怪伍迪拥有的东西。",
        challenge_target_30: "dada.pick()方法可以让嗒嗒捡起地面上的收集物（书或者肉）<br>当嗒嗒靠近树怪伍迪身边时dada.give()方法可以用嗒嗒手里的东西交换树怪伍迪拥有的东西。",
        challenge_target_31: "啪啦靠近叶子怪丽菲的时候会被叶子怪丽菲吓跑，啪啦被吓跑后会通关失败。",
        challenge_target_32: "啪啦可以通过低矮的障碍物（如：草垛，小石墩），但是太高（如：图腾，大石碑）的就过不去了。<br>树怪伍迪在交换到自己喜欢的东西时会走开。",
        challenge_target_33: "可以把所有要重复的步骤都写进while True循环里。",
        challenge_target_34: "if语句是个判断句式，可以解释为如果……就，就像下面这样：<br>如果啪啦在裂隙里，就让啪啦释放冰魔法。<br>if pala.inCrack:<br>    pala.ice()",
        challenge_target_35: "if语句是个判断句式，可以解释为如果……就，就像下面这样：<br>如果啪啦在裂隙里，就让啪啦释放冰魔法。<br>if pala.inCrack:<br>    pala.ice()<br>这样就可以避免啪啦在没有裂隙的地方释放魔法。",
        challenge_target_36: "if语句是个判断语句，可以解释为如果……就，就像下面这样：<br>如果啪啦在裂隙里，就让啪啦释放冰魔法。<br>if pala.inCrack:<br>    pala.ice()<br>我们可以把判断语句写进循环里，用来处理稍微复杂点的情况。",
        challenge_target_37: "if语句是个判断语句，可以解释为如果……就，就像下面这样：<br>如果啪啦在裂隙里，就让啪啦释放冰魔法。<br>if pala.inCrack:<br>    pala.ice()<br>我们可以把判断语句写进循环里，用来处理稍微复杂点的情况。",
        challenge_target_38: "if语句是个判断语句，可以解释为如果……就，就像下面这样：<br>如果啪啦在裂隙里，就让啪啦释放冰魔法。<br>if pala.inCrack:<br>    pala.ice()<br>我们可以把判断语句写进循环里，用来处理稍微复杂点的情况。",
        challenge_target_39: "if语句是个判断语句，可以解释为如果……就，就像下面这样：<br>如果啪啦在裂隙里，就让啪啦释放冰魔法。<br>if pala.inCrack:<br>    pala.ice()<br>我们可以把判断语句写进循环里，用来处理稍微复杂点的情况。",
        challenge_target_40: "if语句是个判断语句，可以解释为如果……就，就像下面这样：<br>如果啪啦在裂隙里，就让啪啦释放冰魔法。<br>if pala.inCrack:<br>    pala.ice()<br>我们可以把判断语句写进循环里，用来处理稍微复杂点的情况。",
        challenge_target_41: "dada.say()<br>调用这个方法可以让嗒嗒说出一个短信息，传入的参数可以是具体的话、数字，也可以是数值类型或字符串类型的变量。<br>pala.mana<br>啪啦的魔法值，最大值为100，最小值为0",
        challenge_target_42: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。",
        challenge_target_43: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_44: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_45: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_46: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_47: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_48: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_49: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_50: "啪啦的魔法值为100，每次填补一个裂隙，消耗30魔法值。当魔法值不足30时啪啦无法释放魔法。<br>pala.recover()<br>调用这个方法后，啪啦回复魔法值10<br>可以根据实际情况增加调用recover()方法的次数。",
        challenge_target_51: "while pala.mana < 100:<br>      pala.recover()<br>当啪啦的魔法值小于100时，就调用pala.recover()。通过这样的方式可以让啪啦重复的使用recover()回复魔法，直到啪啦的魔法值不小于100。",
        challenge_target_52: "while pala.mana < 100:<br>      pala.recover()<br>当啪啦的魔法值小于100时，就调用pala.recover()。通过这样的方式可以让啪啦重复的使用recover()回复魔法，直到啪啦的魔法值不小于100。",
        challenge_target_53: "布尔值包含True（真）和False(假)。<br>我们之前使用的if条件判断，while循环语句后的条件就是布尔值。<br>你可以将这些条件say()出来试试。 ",
        challenge_target_54: "土著马克拥有自己的领地，当嗒嗒进入土著马克的领地时会遭到土著马克的攻击。最好让嗒嗒再土著马克的领地外围等他睡着后再过去。",
        challenge_target_55: "土著马克可能会睡着，他的isSleeping属性会告诉程序他睡着了没有，我们可以用while True循环来不停的判断土著马克的状态，例如：<br>While True：<br>    If masker.isSleeping:<br>        dada.moveRight(5)<br>当土著马克睡着时，啪啦向右移动5个格子的距离",
        challenge_target_56: "土著马克可能会睡着，他的isSleeping属性会告诉程序他睡着了没有，我们可以用while True循环来不停的判断土著马克的状态，例如：<br>While True：<br>    If masker.isSleeping:<br>        dada.moveRight(5)<br>当土著马克睡着时，啪啦向右移动5个格子的距离<br>注意土著马克的领地范围。",
        challenge_target_57: "土著马克可能会睡着，他的isSleeping属性会告诉程序他睡着了没有，我们可以用while True循环来不停的判断土著马克的状态，例如：<br>While True：<br>    If masker.isSleeping:<br>        dada.moveRight(5)<br>当土著马克睡着时，啪啦向右移动5个格子的距离<br>注意土著马克的领地范围。",
        challenge_target_58: "土著马克可能会睡着，他的isSleeping属性会告诉程序他睡着了没有，我们可以用while True循环来不停的判断土著马克的状态，例如：<br>While True：<br>    If masker.isSleeping:<br>        dada.moveRight(5)<br>当土著马克睡着时，啪啦向右移动5个格子的距离<br>注意土著马克的领地范围。",
        challenge_target_59: "土著马克可能会睡着，他的isSleeping属性会告诉程序他睡着了没有，我们可以用while True循环来不停的判断土著马克的状态，例如：<br>While True：<br>    If masker.isSleeping:<br>        dada.moveRight(5)<br>当土著马克睡着时，啪啦向右移动5个格子的距离<br>注意土著马克的领地范围。",
        challenge_target_60: "not 会否定后面的条件，比如：<br>not True 等于 False<br>not False 等于 True<br>如果土著马克没有睡着,那就让嗒嗒等他睡着之后再通过，就像这样：<br>while not masker.isSleeping:<br>    wait()",
        challenge_target_61: "not 会否定后面的条件，比如：<br>not True 等于 False<br>not False 等于 True<br>如果土著马克没有睡着,那就让嗒嗒等他睡着之后再通过，就像这样：<br>while not masker.isSleeping:<br>    wait()",
        challenge_target_62: "not 会否定后面的条件，比如：<br>not True 等于 False<br>not False 等于 True<br>如果土著马克没有睡着,那就让嗒嗒等他睡着之后再通过，就像这样：<br>while not masker.isSleeping:<br>    wait()",
        challenge_target_63: "如果土著马克没有睡着,那就让嗒嗒等他睡着之后再通过，就像这样：<br>while not masker.isSleeping:<br>    wait()<br>鼠标放在土著马克身上会显示他们的序号，可以针对不同的土著马克进行分别判断。",
        challenge_target_64: "and 是“并且”的意思，土著马克0号睡着了并且土著马克1号也睡着了，可以这样写：<br>maskerList[0].isSleeping and maskerList[1].isSleeping",
        challenge_target_65: "and 是“并且”的意思，土著马克0号睡着了并且土著马克1号也睡着了，可以这样写：<br>maskerList[0].isSleeping and maskerList[1].isSleeping",
        challenge_target_66: "or 是“或者”的意思，土著马克睡着了或者土著马克在玩耍可以这样写：<br>masker.isSleeping or masker.isPlaying<br>土著马克睡着或者玩耍嗒嗒都可以通过。",
        challenge_target_67: "or 是“或者”的意思，土著马克睡着了或者土著马克在玩耍可以这样写：<br>masker.isSleeping or masker.isPlaying<br>土著马克睡着或者玩耍嗒嗒都可以通过。",
        challenge_target_68: "or 是“或者”的意思，土著马克睡着了或者土著马克在玩耍可以这样写：<br>masker.isSleeping or masker.isPlaying<br>土著马克睡着或者玩耍嗒嗒都可以通过。",
        challenge_target_69: "not and or 结合着使用可以做更多的事情，当土著马克0号在睡觉或者在玩耍并且土著1号在睡觉或者在玩耍就可以这样写：<br>(maskerList[0].isSleeping or maskerList[0].isPlaying) and <br>(maskerList[1].isSleeping or maskerList[1].isPlaying)",
        challenge_target_70: "not and or 结合着使用可以做更多的事情，当土著马克0号在睡觉或者在玩耍并且土著1号在睡觉或者在玩耍就可以这样写：<br>(maskerList[0].isSleeping or maskerList[0].isPlaying) and <br>(maskerList[1].isSleeping or maskerList[1].isPlaying)",
        challenge_target_71: '变量让你能够把程序中准备使用的每一段数据都赋给一个简短、易于记忆的名字，因此它们十分有用。我们可以给任何数据起一个名字， 比如我们可以给数字8起个名字step，可以这样写：<br>step = 8<br>也可以给土著马克1号起个名字叫Jone：<br>Jone = maskerList[1]<br>甚至我们可以给一句话起个名字：<br>word = "I love dadaCoding!"<br>起完名字之后就可以在后面的代码中使用名字来代替原来的内容，例如可以用Jone.isSleeping来判断刚刚起名叫Jone的土著马克1号是否是睡着的。',
        challenge_target_72: '变量让你能够把程序中准备使用的每一段数据都赋给一个简短、易于记忆的名字，因此它们十分有用。我们可以给任何数据起一个名字， 比如我们可以给数字8起个名字step，可以这样写：<br>step = 8<br>也可以给土著马克1号起个名字叫Jone：<br>Jone = maskerList[1]<br>甚至我们可以给一句话起个名字：<br>word = "I love dadaCoding!"<br>起完名字之后就可以在后面的代码中使用名字来代替原来的内容，例如可以用Jone.isSleeping来判断刚刚起名叫Jone的土著马克1号是否是睡着的。',
        challenge_target_73: "在Python里我们也可以进行一些简单的运算，比如：加（+）减（-）乘（*）除（/），Python还可以进行一些比较复杂的运算，比如：幂运算（**），取模（%），取整除（//）等等。<br>再dadaCoding中我们可以用say()让嗒嗒直接把计算结果说出来，例如：<br>dada.say(9 * 9)<br>也可以把计算结果用变量存储起来，然后通过变量来使用这个结果，例如：<br>result = 9 * 9<br>dada.say(result)",
        challenge_target_74: "在Python里我们也可以进行一些简单的运算，比如：加（+）减（-）乘（*）除（/），Python还可以进行一些比较复杂的运算，比如：幂运算（**），取模（%），取整除（//）等等。<br>再dadaCoding中我们可以用say()让嗒嗒直接把计算结果说出来，例如：<br>dada.say(9 * 9)<br>也可以把计算结果用变量存储起来，然后通过变量来使用这个结果，例如：<br>result = 9 * 9<br>dada.say(result)",
        challenge_target_75: "在Python里我们也可以进行一些简单的运算，比如：加（+）减（-）乘（*）除（/），Python还可以进行一些比较复杂的运算，比如：幂运算（**），取模（%），取整除（//）等等。<br>再dadaCoding中我们可以用say()让嗒嗒直接把计算结果说出来，例如：<br>dada.say(9 * 9)<br>也可以把计算结果用变量存储起来，然后通过变量来使用这个结果，例如：<br>result = 9 * 9<br>dada.say(result)",
        challenge_target_76: "在Python里我们也可以进行一些简单的运算，比如：加（+）减（-）乘（*）除（/），Python还可以进行一些比较复杂的运算，比如：幂运算（**），取模（%），取整除（//）等等。<br>再dadaCoding中我们可以用say()让嗒嗒直接把计算结果说出来，例如：<br>dada.say(9 * 9)<br>也可以把计算结果用变量存储起来，然后通过变量来使用这个结果，例如：<br>result = 9 * 9<br>dada.say(result)",
        challenge_target_77: "在Python里我们也可以进行一些简单的运算，比如：加（+）减（-）乘（*）除（/），Python还可以进行一些比较复杂的运算，比如：幂运算（**），取模（%），取整除（//）等等。<br>再dadaCoding中我们可以用say()让嗒嗒直接把计算结果说出来，例如：<br>dada.say(9 * 9)<br>也可以把计算结果用变量存储起来，然后通过变量来使用这个结果，例如：<br>result = 9 * 9<br>dada.say(result)",
        challenge_target_78: "object.moveTo()<br>走向某个目标（对象，或者坐标），object.moveTo(x, y)表示移动到某个坐标的位置,object.moveTo(object)表示移动到某个对象的位置。",
        challenge_target_79: "object.moveTo()<br>走向某个目标（对象，或者坐标），object.moveTo(x, y)表示移动到某个坐标的位置,object.moveTo(object)表示移动到某个对象的位置。",
        challenge_target_80: "请求帮助",
        challenge_target_81: "",
        challenge_target_82: "",
        challenge_target_83: "",
        challenge_target_84: "",
        challenge_target_85: "",
        challenge_target_86: "",
        challenge_target_87: "",
        challenge_target_88: "",
        challenge_target_89: "",
        challenge_target_90: "",
        challenge_target_91: "",
        challenge_target_92: "",
        challenge_target_93: "",
        challenge_target_94: "",
        challenge_target_95: "",
        challenge_target_96: "",
        challenge_target_97: "",
        challenge_target_98: "",
        challenge_target_99: "",
        challenge_target_100: "",
        challenge_target_101: "",
        challenge_target_102: "",
        challenge_target_103: "",
        challenge_target_104: "",
        challenge_target_105: "",
        challenge_target_106: "",
        challenge_target_107: "",
        challenge_target_108: "",
        challenge_target_109: "",
        challenge_target_110: "",
        challenge_target_111: "",
        challenge_target_112: "",
        challenge_target_113: "",
        challenge_target_114: "",
        challenge_target_115: "",
        challenge_target_116: "",
        challenge_target_117: "",
        challenge_target_118: "",
        challenge_target_119: "",
        challenge_target_120: "",
        challenge_target_121: "",
        challenge_target_122: "",
        challenge_target_123: "",
        challenge_target_124: "",
        challenge_target_125: "",
        challenge_target_126: "",
        challenge_target_127: "",
        challenge_target_128: "",
        challenge_target_129: "",
        challenge_target_130: "",
        challenge_target_131: "",
        challenge_target_132: "",
        challenge_target_133: "",
        challenge_target_134: "",
        challenge_target_135: "",
        challenge_target_136: "",
        challenge_target_137: "",
        challenge_target_138: "",
        challenge_target_139: "",
        challenge_target_140: "",
        challenge_target_141: "",
        challenge_target_142: "",
        challenge_target_143: "",
        challenge_target_144: "",
        challenge_target_145: "",
        challenge_target_146: "",
        challenge_target_147: "",
        challenge_target_148: "",
        challenge_target_149: "",
        challenge_target_150: "",
        challenge_target_151: "",
        challenge_target_152: "",
        challenge_target_153: "",
        challenge_target_154: "",
        challenge_target_155: "",
        challenge_target_156: "",
        challenge_target_157: "",
        challenge_target_158: "",
        challenge_target_159: "",
        challenge_target_160: "",
        challenge_target_161: "",
        challenge_target_162: "",
        challenge_target_163: "不要让小精灵啪啦靠近叶子怪丽菲周围一圈的距离，注意啪啦的前进路线。",
        challenge_target_164: "不要让小精灵啪啦靠近叶子怪丽菲周围一圈的距离，注意啪啦的前进路线。",
        challenge_target_165: "不要让小精灵啪啦靠近叶子怪丽菲周围一圈的距离，注意啪啦的前进路线。",
        challenge_target_166: "while pala.mana < 100:<br>      pala.recover()<br>当啪啦的魔法值小于100时，就调用pala.recover()。通过这样的方式可以让啪啦重复的使用recover()回复魔法，直到啪啦的魔法值不小于100。",
        challenge_target_167: "while pala.mana < 100:<br>      pala.recover()<br>当啪啦的魔法值小于100时，就调用pala.recover()。通过这样的方式可以让啪啦重复的使用recover()回复魔法，直到啪啦的魔法值不小于100。",
        challenge_target_168: "",
        challenge_target_169: "",
        challenge_target_170: "",
        challenge_target_171: "",
        challenge_target_172: "<br>",
        challenge_target_173: "",
        challenge_target_174: '变量让你能够把程序中准备使用的每一段数据都赋给一个简短、易于记忆的名字，因此它们十分有用。我们可以给任何数据起一个名字， 比如我们可以给数字8起个名字step，可以这样写：<br>step = 8<br>也可以给土著马克1号起个名字叫Jone：<br>Jone = maskerList[1]<br>甚至我们可以给一句话起个名字：<br>word = "I love dadaCoding!"<br>起完名字之后就可以在后面的代码中使用名字来代替原来的内容，例如可以用Jone.isSleeping来判断刚刚起名叫Jone的土著马克1号是否是睡着的。',
        challenge_target_175: '变量让你能够把程序中准备使用的每一段数据都赋给一个简短、易于记忆的名字，因此它们十分有用。我们可以给任何数据起一个名字， 比如我们可以给数字8起个名字step，可以这样写：<br>step = 8<br>也可以给土著马克1号起个名字叫Jone：<br>Jone = maskerList[1]<br>甚至我们可以给一句话起个名字：<br>word = "I love dadaCoding!"<br>起完名字之后就可以在后面的代码中使用名字来代替原来的内容，例如可以用Jone.isSleeping来判断刚刚起名叫Jone的土著马克1号是否是睡着的。',
        challenge_target_176: "",
        challenge_target_177: "",
        challenge_target_178: "",
        challenge_target_179: "",
        challenge_target_180: "",
        challenge_target_181: "",
        challenge_prompt_2: "传送门离嗒嗒有点远呢，我们一起帮助他吧。",
        challenge_prompt_3: "难度升级了哦，上下左右走起来。",
        challenge_prompt_4: "接下来要靠你自己来编写整个代码喽。我相信你一定办得到！加油！",
        challenge_prompt_5: "数一数通往成功的道路一共有几步哦！",
        challenge_prompt_6: "小心，不要掉下去了！数一数要移动几格。",
        challenge_prompt_7: "只要改一个地方就过关了。",
        challenge_prompt_8: "这关我猜你“应该”过不了！",
        challenge_prompt_9: "新技巧：循环while True！这是一个让你的代码重复执行的好方法。",
        challenge_prompt_10: "虽然这个方法很好用，但是你也要注意方向",
        challenge_prompt_11: "要注意方法的调用，while True指令的使用规则哦，如：缩进。",
        challenge_prompt_12: "注意：并不是一开始就要使用while True循环指令哦！",
        challenge_prompt_13: "让我看看你能不能使用循环的方式来写出一段完整的代码！",
        challenge_prompt_14: "考验眼力的时候到了，你能看的清路线吗？",
        challenge_prompt_15: "点击“运行”，看看小精灵啪啦的魔法。",
        challenge_prompt_16: "你也可以对啪啦使用ice()的指令来施魔法填补裂隙哦！",
        challenge_prompt_17: "达到传送阵的路线有很多种，你需要选择最简洁的方法。",
        challenge_prompt_18: "只需要填补一个裂隙哦，不要让嗒嗒掉“坑”里去了。",
        challenge_prompt_19: "要与小精灵“啪啦”通力合作哦，帮嗒嗒通过传送阵，寻找水晶碎片。",
        challenge_prompt_20: "记得要善用小精灵“啪啦”来完成任务哦！",
        challenge_prompt_21: "皇天不负有心人，终于出现水晶碎片了，赶紧去获得水晶碎片吧！",
        challenge_prompt_22: "试试能不能靠自己的能力获得水晶碎片。",
        challenge_prompt_23: "想要获得水晶碎片，需要与啪啦通力合作哦！",
        challenge_prompt_24: "掌握循环while True，你很快就会了解，学会这个知识点，将是多么的方便！",
        challenge_prompt_25: "需要把“啪啦”施魔法ice()和循环while True指令并存，你行吗？",
        challenge_prompt_26: "把书捡起来给树怪伍迪（Woody）吧！",
        challenge_prompt_27: "把书交给树怪伍迪它就会很开心了。",
        challenge_prompt_28: "继续与树怪伍迪过招吧！",
        challenge_prompt_29: "要弄清楚这一关的先后顺序，否则树怪伍迪会拦着路不让你通过的。",
        challenge_prompt_30: "注意哦，有两个树怪伍迪需要交换物品。接下来你需要好好利用捡起pickUp()和给give()这两个指令哦。",
        challenge_prompt_31: "吼吼，叶子怪丽菲（Leafy）要把啪啦给吓跑了，不要让啪啦离叶子怪丽菲太近了。",
        challenge_prompt_32: "这么多的叶子怪丽菲，太可怕了，怎么样的路线才能让啪啦远离叶子怪丽菲呢？",
        challenge_prompt_33: "路线很复杂，要理性分析哦",
        challenge_prompt_34: "学习新知识：if语句，不能随便使用小精灵啪啦的魔法哦。",
        challenge_prompt_35: "我们需要学会判断，只有地上有裂隙的时候，啪啦才需要施魔法，否则只会成为障碍",
        challenge_prompt_36: "学会判断的逻辑，对生活会有很大的帮助哦。",
        challenge_prompt_37: "有的水晶碎片是在地块上的，就不需要再让啪啦施魔法填补地块了，注意哦，否则就拿不到水晶碎片了。",
        challenge_prompt_38: "叶子怪这么多，可不要被吓到才好，注意啪啦的路线。",
        challenge_prompt_39: "一步一个脚印，只有避开叶子怪，跟着啪啦走，才能到达传送门",
        challenge_prompt_40: "这一关路线太复杂，想要避开所有的叶子怪需要仔细思考，可以看看我们为你画出来的路线。",
        challenge_prompt_41: "小精灵离开森林，魔法值（mana）可能会不够用呦！",
        challenge_prompt_42: "啪啦的魔法值为100，每填补一个裂隙，就要消耗30。学会用say这个指令来显示小精灵的魔法值。",
        challenge_prompt_43: "啪啦啪啦，嘛咪嘛咪哄，魔法带我通向传送阵，小心，传送阵也在裂隙中哦。",
        challenge_prompt_44: "啪啦每一次施法后，记得给它恢复魔法值哦！学会使用recover()来恢复啪啦的魔法值",
        challenge_prompt_45: "再循环中给啪啦恢复魔法值，就不用担心有不能通过的裂隙了。",
        challenge_prompt_46: "你能让啪啦将这三个不相干的地块连接在一起吗？",
        challenge_prompt_47: "把学到的知识都用起来吧，你可以通过这一关的。",
        challenge_prompt_48: "根据嗒嗒的路线来确定啪啦的路线，这样能节省不少的时间哦。",
        challenge_prompt_49: "这样的独木桥，第一次走吧，跟着啪啦循环走起来，小心一点啊！",
        challenge_prompt_50: "可怕的叶子怪们又来了，啪啦的路线可要仔细想一想了！",
        challenge_prompt_51: "100点魔法值，加满！",
        challenge_prompt_52: "选择正确的路径是得到三星的重要条件之一！",
        challenge_prompt_53: "学习新知识了，利用布尔值，真（True）或者假（False）来判断啪啦在哪里需要施放魔法，用嗒嗒的say看看吧。",
        challenge_prompt_54: "土著马克并不那么友好，还是趁它睡着了再过去吧！",
        challenge_prompt_55: "用if指令来静待土著睡觉吧…",
        challenge_prompt_56: "没有任何怪兽可以阻挡我们搜集宝贵的水晶碎片。",
        challenge_prompt_57: "糟了，请小心，土著马克又出现了！你还记得之前的if指令吗！",
        challenge_prompt_58: "我的天呀！它们有两只?",
        challenge_prompt_59: "一环套一环，不过，不要忘记等待土著马克睡着。",
        challenge_prompt_60: "学习新知识了，not、wait()等着吧，与之前的判断可不同哦，如果土著马克没睡着，就要一直等着。",
        challenge_prompt_61: "小心不要把土著马克吵醒了！",
        challenge_prompt_62: "土著马克没睡着，我们就要一直等着，你试试看！",
        challenge_prompt_63: "小心！有两个土著马克，要分别的避开它们，不要与它们打起来，你打不过的。",
        challenge_prompt_64: "小声的把正确答案说出来吧，因为不能吵醒土著马克哦。",
        challenge_prompt_65: "利用not指令，想一想括号()里需要填写什么内容！",
        challenge_prompt_66: "土著马克不仅是个瞌睡虫，他们还很贪玩哟，当土著马克在睡觉isSleeping或者玩耍isPlaying时，嗒嗒都可以通过的。",
        challenge_prompt_67: "三个土著都要注意哦！",
        challenge_prompt_68: "开始你的表演，这一关卡，除了小精灵啪啦，没人能帮你！",
        challenge_prompt_69: "想要拿到所有的水晶碎片还是有些难度的，但是如果把之前的知识点回忆一下，就能轻松过关。",
        challenge_prompt_70: "这一关是之前的知识点大集合，啪啦施法、等待土著马克睡着，给树怪伍迪礼物，最后通关，加油！",
        challenge_prompt_71: "新知识来了，variable变量，注意带入正确的数字哦！",
        challenge_prompt_72: "转圈圈，哈哈哈，学会variable变量，一切都变得如此简单。",
        challenge_prompt_73: "这里有7个水晶碎片！",
        challenge_prompt_74: "变量也可以用来取代你不知道的数目。",
        challenge_prompt_75: '给"字符串"起个别名！<br>（坐标计算可是个高级技巧哟）',
        challenge_prompt_76: "树怪伍迪Woody想要哪一个物品呢？书还是肉肉呢，你需要作出判断并且用坐标的知识点来完成。",
        challenge_prompt_77: "寻找树怪伍迪Woody想要的物品吧，可是物品在哪呢？想一想，用什么方法能找到它。",
        challenge_prompt_78: "moveTo()，非常好用，一定会让你很开心的。",
        challenge_prompt_79: "你需要在嗒嗒和啪啦身上熟练的使用moveTo()，这样才能用最简单的代码来通过传送门。",
        challenge_prompt_80: "",
        challenge_prompt_81: "",
        challenge_prompt_82: "",
        challenge_prompt_83: "",
        challenge_prompt_84: "",
        challenge_prompt_85: "",
        challenge_prompt_86: "",
        challenge_prompt_87: "",
        challenge_prompt_88: "",
        challenge_prompt_89: "",
        challenge_prompt_90: "",
        challenge_prompt_91: "",
        challenge_prompt_92: "",
        challenge_prompt_93: "",
        challenge_prompt_94: "",
        challenge_prompt_95: "",
        challenge_prompt_96: "",
        challenge_prompt_97: "",
        challenge_prompt_98: "",
        challenge_prompt_99: "",
        challenge_prompt_100: "",
        challenge_prompt_101: "",
        challenge_prompt_102: "",
        challenge_prompt_103: "",
        challenge_prompt_104: "",
        challenge_prompt_105: "",
        challenge_prompt_106: "",
        challenge_prompt_107: "",
        challenge_prompt_108: "",
        challenge_prompt_109: "",
        challenge_prompt_110: "",
        challenge_prompt_111: "",
        challenge_prompt_112: "",
        challenge_prompt_113: "",
        challenge_prompt_114: "",
        challenge_prompt_115: "",
        challenge_prompt_116: "",
        challenge_prompt_117: "",
        challenge_prompt_118: "",
        challenge_prompt_119: "",
        challenge_prompt_120: "",
        challenge_prompt_121: "",
        challenge_prompt_122: "",
        challenge_prompt_123: "",
        challenge_prompt_124: "",
        challenge_prompt_125: "",
        challenge_prompt_126: "",
        challenge_prompt_127: "",
        challenge_prompt_128: "",
        challenge_prompt_129: "",
        challenge_prompt_130: "",
        challenge_prompt_131: "",
        challenge_prompt_132: "",
        challenge_prompt_133: "",
        challenge_prompt_134: "",
        challenge_prompt_135: "",
        challenge_prompt_136: "",
        challenge_prompt_137: "",
        challenge_prompt_138: "",
        challenge_prompt_139: "",
        challenge_prompt_140: "",
        challenge_prompt_141: "",
        challenge_prompt_142: "",
        challenge_prompt_143: "",
        challenge_prompt_144: "",
        challenge_prompt_145: "",
        challenge_prompt_146: "",
        challenge_prompt_147: "",
        challenge_prompt_148: "",
        challenge_prompt_149: "",
        challenge_prompt_150: "",
        challenge_prompt_151: "",
        challenge_prompt_152: "",
        challenge_prompt_153: "",
        challenge_prompt_154: "",
        challenge_prompt_155: "",
        challenge_prompt_156: "",
        challenge_prompt_157: "",
        challenge_prompt_158: "",
        challenge_prompt_159: "",
        challenge_prompt_160: "",
        challenge_prompt_161: "",
        challenge_prompt_162: "",
        challenge_prompt_163: "远远看去，全是叶子怪丽菲，啪啦该如何是好，观察清楚再行动。",
        challenge_prompt_164: "好像只有一条路可以走，用排除法试试？",
        challenge_prompt_165: "这一关厉害了，两边都可以哦！",
        challenge_prompt_166: "注意保持足够的魔法值，这样才能应对突发状况！",
        challenge_prompt_167: "地块会指引你前进的方向！",
        challenge_prompt_168: "",
        challenge_prompt_169: "",
        challenge_prompt_170: "",
        challenge_prompt_171: "",
        challenge_prompt_172: "",
        challenge_prompt_173: "",
        challenge_prompt_174: "给对象起个自己喜欢的名字吧！",
        challenge_prompt_175: "通过名字来查看土著是不是睡着了，感觉代码都短了很多呢！",
        challenge_prompt_176: "",
        challenge_prompt_177: "",
        challenge_prompt_178: "",
        challenge_prompt_179: "",
        challenge_prompt_180: "",
        challenge_prompt_181: "",
        room_page_name: "%p0的教室",
        room_page_progress: "进度",
        room_page_lesson: "课程",
        room_page_score_table: "成绩表",
        room_page_practise: "课后练习",
        room_page_student_info: "学生信息",
        room_page_progress_limit: "进度限制",
        room_page_data_export: "将数据导出",
        room_page_create_number: "创建学生账户",
        room_page_chapter: "第%p0章",
        room_page_choose_lesson: "课程选择",
        room_page_opening: "开放",
        room_page_cancel: "取消",
        room_page_subject: "按科目分级",
        room_page_student_average: "学生平均进度",
        room_page_assessment_average: "评估中的平均评分",
        room_page_difficulty_game: "困难的关卡",
        room_page_count: "统计",
        room_page_difficulty_game_show: "困难的关卡展示",
        room_page_export_score: "导出成绩表",
        room_page_lead_in_student: "导入学生信息",
        room_page_lead_out_this_room: "导出该教室数据",
        room_page_manage_this_room: "管理此教室的学生账户",
        room_page_student_name: "名称",
        room_page_student_login_name: "登录名",
        room_page_student_pwd: "密码",
        room_page_student_file: "归档",
        room_page_student_move: "移动",
        room_page_student_delete: "删除",
        room_page_save: "保存",
        room_page_close: "关闭",
        room_page_yes: "确定",
        room_page_common_teacher: "共同老师",
        room_page_send_invite: "发送邀请",
        room_page_teacher: "教师",
        room_page_login_email: "登陆邮箱",
        room_page_edit: "编辑",
        teacher_page_my_room: "我的教室",
        teacher_page_file_room: "存档教室",
        teacher_page_create_time: "创建时间",
        teacher_page_file_time: "存档时间",
        teacher_page_file_explain: "存档说明",
        teacher_page_operate: "操作",
        teacher_page_read_file: "读档",
        teacher_page_regin: "恢复",
        teacher_page_file_room_already: "已存档的教室",
        teacher_page_file_student_already: "已存档的学生",
        teacher_page_look_file_student: "查看已被归档的学生",
        teacher_page_my_badge: "我的徽章",
        teacher_page_continue_game: "继续我的游戏",
        teacher_page_share: "分享",
        teacher_page_add_new_practise: "添加新的课后练习",
        teacher_page_my_collect: "我的收藏",
        teacher_page_teacher_resource: "教师资源中心",
        student_page_welcome_back: "欢迎回来%p0同学",
        student_page_copy: "复制",
        student_page_which_room: "%p0班的教室",
        student_page_teacher_share: "老师分享的课后练习",
        student_page_student_share: "同学分享的课后练习",
        student_chapter_prompt_0: "这不可能",
        student_chapter_prompt_1: "第一章通关后解锁",
        student_chapter_prompt_2: "第二章通关后解锁",
        student_chapter_prompt_3: "敬请期待",
        file_page_original_room: "原属教室",
        file_page_reset_password: "重置密码",
        t_information_teacher_info: "教师详情",
        t_information_last_login: "最近登录时间",
        t_information_type: "身份",
        t_information_related_room: "关联教室",
        t_information_login_this: "登录该教师账号",
        t_information_edit_info: "修改该教师资料",
        room_information_room_info: "教室详情",
        room_information_room_name: "教室名称",
        room_information_room_seat: "教室座位",
        room_information_telated_teacher: "关联老师",
        room_information_room_type: "教室类型",
        room_information_start_lesson: "开课时间",
        room_information_end_time: "到期时间",
        room_information_look_room: "到该教室查看",
        room_information_edit_room: "修改该教室信息",
        my_number_code: "我的账号",
        my_number_name: "我的昵称",
        my_number_original_pwd: "请输入原始密码",
        my_number_new_pwd: "请输入新密码",
        my_number_new_pwd_ok: "确认新密码",
        my_number_my_lesson: "我的课程",
        my_number_lesson_type: "课程类型",
        my_number_begin_time: "开始时间",
        my_number_charge_type: "收费方式",
        my_number_delete_code: "删除我的账号",
        my_number_whose_code: "%p0的账号",
        all_user_home_page: "首页",
        all_user_end_page: "尾页",
        all_user_prev_page: "上一页",
        all_user_next_page: "下一页",
        all_user_which_page: "第%p0页",
        all_user_all_page: "共%p0页",
        all_user_click_login: "点击登陆",
        all_user_click_edit: "点击编辑",
        index_try_to_learn: "立即试学",
        index_consult: "咨询",
        index_price_explain: "价格说明",
        index_our_team: "我们的团队",
        index_home_page: "首&nbsp;&nbsp;&nbsp;页",
        index_pipaprogram: "嗒嗒编程",
        index_teaching_mode: "教学模式",
        index_buy_lessons: "购买课程",
        order_wxpay_scan_amount: "订单金额:",
        order_wxpay_scan_prompt: "请使用微信扫一扫，扫描二维码支付！",
        order_wxpay_scan_source: "本支付服务由亦果亦朵提供",
        dialog_system_0: "在这个神奇大陆上，人们过着平静的生活。",
        dialog_system_1: "有一天火山喷发了，水晶被喷起后散落在大陆各地。",
        dialog_system_2: "地下世界的小怪物们涌了出来，到处乱跑。",
        dialog_system_3: "小飞侠嗒嗒肩负收集齐水晶碎片的重任，独自踏上旅行。",
        dialog_system_4: "救命呀，救命呀！小鬼！别傻站着看，快帮我出去啊！",
        dialog_system_5: "你是……精灵吗？好可爱！",
        dialog_system_6: "我看你是想尝尝我正义的铁拳了！敢说我啪啦可爱！",
        dialog_system_7: "啪……啪啦,名字也很可爱噢。",
        dialog_system_8: "少啰嗦！你怎么会在这儿？这儿可不是人类该待的地方。",
        dialog_system_9: "火山爆发，怪物出没，村子毁了，我就一路寻找水晶碎片，想要封住火山洞口，阻挡怪物再出来。",
        dialog_system_10: "哼哼，你个小不点胆子还挺大，不过在我们这里光有胆量可不行，我给你带路吧，我可以把过不去的路铺平，方便你通过。",
        dialog_system_11: "太棒了！我在这里绕半天都走不出去，正着急呢。",
        dialog_system_12: "森林尽头一直发着奇怪的光，我也正想去看看，可能是颗大水晶。",
        dialog_system_13: "太好了！向奇怪的光，前进！！",
        dialog_system_14: "你这小鬼，知道精灵之森有多危险吗！？附近就有讨厌的叶子怪，森林深处不知道有什么东西等着我们呢！",
        dialog_system_15: "有你在，怕什么啊~",
        dialog_system_16: "哼哼，小鬼还挺有眼光嘛！那出发吧！",
        dialog_system_17: "哇，找了这么久，终于找到了传说中的水晶碎片。",
        dialog_system_18: "这就是你要找的水晶碎片啊？它有那么大的能量能封印火山洞口？",
        dialog_system_19: "这只是一小块碎片，我们需要找到很多很多的水晶碎片，才能补住洞口。",
        dialog_system_20: "那我们赶紧收集起来吧。",
        dialog_system_21: "有些厚脸皮的惊叫树怪，喜欢跟过路人要礼物，如果收到不喜欢的东西，它可会不高兴，更不会让路的。",
        dialog_system_22: "不知道他喜欢什么，只能碰运气了。",
        dialog_system_23: "等一下！或许这场灾难和水晶没关系，我们去……去别的地方找找原因。",
        dialog_system_24: "你在说什么啊，我一路收集水晶，眼看就要找到大水晶了怎么能放弃呢？",
        dialog_system_25: "你懂什么！这里很多叶子怪，喜欢吓人玩，我最最最讨厌吓人这套把戏了！！",
        dialog_system_26: "哈哈~你这么怕他们吗？那我们小心点树丛好了。",
        dialog_system_27: "你少得意啦！待会遇到看你还笑不笑得出！",
        dialog_system_28: "我想，这可能不是全部的水晶。",
        dialog_system_29: "你怎么知道？我们可是找遍了森林的每个角落啊！",
        dialog_system_30: "这么点水晶，怎么可能封得住怪物出口，肯定不止森林，真正的冒险也许才刚刚开始呢！",
        dialog_system_31: "你会陪我一起吗？",
        dialog_system_32: "当然！可是过了森林就是“落寞之地”，我们从小被告诫那边很危险，不能踏出森林半步……听说那里过着和我们完全不同的生活，我也很好奇！",
        dialog_system_33: "你这个家伙，忍不住想要抱你一下！mua!",
        dialog_system_34: "走开啦你，肉麻死了！",
        dialog_system_35: "赶紧把收集的水晶复原吧！",
        dialog_system_36: "这些臭家伙，我一定要打败他们！",
        dialog_system_37: "每次被打的哇哇大哭的是谁，我们还是等他们睡着了再悄悄溜过去吧！"
    }
};