const acetip=[
    //人物方法
    {
        id:1,
        text:"IronMan",
        caution:"输入正确"
    },
    {
        id:2,
        text:"I",
        caution:"请输入正确的方法ronMan"
    },
    {
        id:3,
        text:"Ir",
        caution:"请输入正确的方法onMan"
    },
    {
        id:4,
        text:"Iro",
        caution:"请输入正确的方法nMan"
    },
    {
        id:5,
        text:"Iron",
        caution:"请输入正确的方法Man"
    },
    {
        id:6,
        text:"IronM",
        caution:"请输入正确的方法an"
    },
    {
        id:7,
        text:"IronMa",
        caution:"请输入正确的方法n"
    },
    //游戏方法_goleft()
    {
        id:8,
        text:"IronMan.goLeft()",
        caution:"正确的方法"
    },
    {
        id:9,
        text:"IronMan.g",
        caution:"请补全正确的方法"
    },
    {
        id:10,
        text:"IronMan.go",
        caution:"请补全正确的方法"
    },
    {
        id:11,
        text:"IronMan.goL",
        caution:"请在后面输入eft()"
    },
    {
        id:12,
        text:"IronMan.goLe",
        caution:"请在后面输入ft()"
    },
    {
        id:13,
        text:"IronMan.goLef",
        caution:"请在后面输入t()"
    },
    {
        id:14,
        text:"IronMan.goLeft",
        caution:"请在后面输入()"
    },
    {
        id:15,
        text:"IronMan.goLeft(",
        caution:"请在后面输入)" 
    },
    //goRight
    {
        id:16,
        text:"IronMan.goRight()",
        caution:"输入正确" 
    },
    {
        id:17,
        text:"IronMan.g",
        caution:"请在后面输入oRight()" 
    },
    {
        id:18,
        text:"IronMan.go",
        caution:"请在后面输入Right()" 
    },
    {
        id:19,
        text:"IronMan.goR",
        caution:"请在后面输入ight()" 
    },
    {
        id:20,
        text:"IronMan.goRi",
        caution:"请在后面输入ght()" 
    },
    {
        id:21,
        text:"IronMan.goRig",
        caution:"请在后面输入ht()" 
    },
    {
        id:22,
        text:"IronMan.goRigh",
        caution:"请在后面输入t()" 
    },
    {
        id:23,
        text:"IronMan.goRight",
        caution:"请在后面输入()" 
    },
    {
        id:24,
        text:"IronMan.goRight(",
        caution:"请在后面输入)" 
    },
    //goup
    {
        id:25,
        text:"IronMan.goUp()",
        caution:"输入正确" 
    },

    {
        id:26,
        text:"IronMan.goU",
        caution:"请在后面输入p()" 
    },
    {
        id:27,
        text:"IronMan.goUp",
        caution:"请在后面输入()" 
    },
    {
        id:28,
        text:"IronMan.goUp(",
        caution:"请在后面输入)" 
    },
    //goDown
    {
        id:29,
        text:"IronMan.goD",
        caution:"请在后面输入own()" 
    },
    {
        id:30,
        text:"IronMan.goDo",
        caution:"请在后面输入wn()" 
    },
    {
        id:31,
        text:"IronMan.goDow",
        caution:"请在后面输入n()" 
    },
    {
        id:32,
        text:"IronMan.goDown",
        caution:"请在后面输入()" 
    },
    {
        id:33,
        text:"IronMan.goDown(",
        caution:")" 
    }
    //
   
]